#!/usr/bin/env bash
set -eo pipefail

macaddresstool-wrapper(){
  if [[ -z "${MACADDRESSIO_API_KEY}" ]]; then
    echo "Please set the MACADDRESSIO_API_KEY env var e.g. export MACADDRESSIO_API_KEY='<YOUR_API_KEY>'"
    exit 1
  fi
    docker run --rm --env-file <(env | grep MACADDRESS) rtluckie/macaddresstool:latest macaddresstool "$@"
}

macaddresstool-wrapper "$@"
